spring:
  application:
    name: EmotionApp
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/emotionApp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hrup041001.
#mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#redis配置

# JWT配置
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24小时
